# Generated by Django 5.2.2 on 2026-07-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacio_personal', '0001_initial'),
        ('recursos_digitales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='recursos_digitales.recursodigital'),
        ),
    ]
