# Generated by Django 5.2.2 on 2026-07-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacio_personal', '0002_initial'),
        ('recursos_digitales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='colecciones', to='recursos_digitales.recursodigital'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcado_como_favorito_por', to='recursos_digitales.recursodigital'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coleccion',
            unique_together={('propietario', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'recurso')},
        ),
    ]
