# Generated by Django 5.2.2 on 2026-07-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompartidoCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compartido', models.DateTimeField(auto_now_add=True)),
                ('fecha_revocado', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'recursos compartidos',
                'ordering': ['-fecha_compartido'],
            },
        ),
    ]
