# Generated by Django 5.2.2 on 2026-07-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interacciones', '0001_initial'),
        ('recursos_digitales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compartidocon',
            name='compartido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_que_comparti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compartidocon',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='recursos_digitales.recursodigital'),
        ),
        migrations.AddField(
            model_name='compartidocon',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_compartidos_conmigo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='compartidocon',
            unique_together={('recurso', 'usuario')},
        ),
    ]
