# Generated by Django 5.2.2 on 2026-07-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_digitales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recursodigital',
            name='autor_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_autoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='recursos_digitales.categoria'),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='recursos_digitales.etiqueta'),
        ),
        migrations.AddField(
            model_name='recursodigital',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_propios', to=settings.AUTH_USER_MODEL),
        ),
    ]
